version: "3.8"

x-common-variables: &db-settings
  POSTGRES_USER: ${POSTGRES_USER}
  POSTGRES_DB: ${POSTGRES_DB}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  POSTGRES_PORT: ${POSTGRES_PORT}

services:
  db:
    image: postgres:alpine
    restart: unless-stopped
    environment:
      <<: *db-settings
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/posgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
  backend:
    build:
      context: .
    restart: unless-stopped
    environment:
      <<: *db-settings
      POSTGRES_HOST: db
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
    command: daphne -b 0.0.0.0 -p 8000 backend.asgi:application
    depends_on:
      db:
        condition: service_healthy
volumes:
  pgdata: